### ISSUE TITLE
pivot operation

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dbt-automation#105]
Write an operation which takes the parameters

- model name: str
- column: str
- values: list[str]

and generates the dbt sql to pivot the table 

Ref: https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/pivot.sql

**Comment by Ishankoradia** [comment]
@fatchat for the pivot operation, are we going to ask user to select the values they want to pivot ? I think we should. 
There can be a check all options if they want all values
